#!/bin/sh
# autopkgtest check
# (C) 2014 Anton Gladky <gladk@debian.org>

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR

freecadcmd --console --run-test 0
echo "run: OK"
